module.exports.descriptions =  {
    error: [
        '',
        'SC INTERRUPT',
        'FI_ERROR',
        'TIMEOUT',
        'DRIVE-TIME ERROR',
        'NOT IN LEVEL',
        'NO DOORZONE',
        'Early dooropening is missing',
        'Dooropen switch is missing',
        'Doorclosed switch is missing',
        'MEMORY_IMAGE',
        'MOTOR_TEMPERATURE',
        'CANFLAG_OFF',
        'CANFLAG_PASSIVE',
        'CANFLAG_OVERFLOW',
        'CANFLAG_Rxbuffer overflow',
        'CANFLAG_Txbuffer overflow',
        'RELEVELING_TRY',
        'RELEVELING NOT IN LEVEL',
        'INTERNAL_ERROR',
        'BYPASS_SC_ERROR',
        '',
        'RECALL',
        'UNKNOWN',
        'DOOR_CLOSED_SC_MISSING',
        'AWM_CABIN_LIGHT',
        'AWM_LEVEL_ERROR',
        'AWM_BYPASS_SC_ERROR',
        'QSPI ERROR',
        '',
        'RECALL_BYPASS',
        'RECALL_BUTTON_NO',
        'RECALL_BUTTON_NC',
        'ENCODER PSU',
        'CABIN_INSPBUTTON',
        'PIT_INSPBUTTON',
        'BYPASS CONNECTOR',
        'START_UP_ERROR',
        'QUICKSTOP',
        'UCM ERROR',
        '',
        'PSU-Bypass Error',
        '',
        'Braketest: Movement detected',
        'Braketest: not executed',
        'OVG relay is not energized',
        'OVG relay has not dropped out',
    ],
    info: [
        'CanOpenBus Init',
        'initialization',
        'Inspection',
        'Inspection drive',
        '',
        'Wait for call',
        'Call available',
        'Normal drive',
        'Landing phases',
        'In destination',
        'Assembly mode',
        'Door stays open',
        '',			
        'FireFightingMode',
        '',
        '',
        '',
        '',
        'Overload',
        'Driving stop',
        'Escape fire',
        'Engine overheat',
        'Start up',
        '',
        'Out of Order',
        'EmergencyPower',
        'Shaft drive',
        'AutomaticEvac.',
        'EmergencyEvac.',
        'Wait for guest',
        'Fill all mode',
    ],
    para: [],
}